#ifndef _THIS_PROJECT_H_
#define _THIS_PROJECT_H_
/* Automatically generated file: do not modify! */
#include "WL_2D_MASS_VERSION.h"
#include "ElementsKernel/Version.h"
#define THIS_PROJECT_MAJOR_VERSION WL_2D_MASS_MAJOR_VERSION
#define THIS_PROJECT_MINOR_VERSION WL_2D_MASS_MINOR_VERSION
#define THIS_PROJECT_PATCH_VERSION WL_2D_MASS_PATCH_VERSION
#define THIS_PROJECT_VERSION CALC_ELEMENTS_VERSION(THIS_PROJECT_MAJOR_VERSION,THIS_PROJECT_MINOR_VERSION,THIS_PROJECT_PATCH_VERSION)
#define THIS_PROJECT_VERSION_STRING Elements::getVersionString(THIS_PROJECT_MAJOR_VERSION,THIS_PROJECT_MINOR_VERSION,THIS_PROJECT_PATCH_VERSION)
#define THIS_PROJECT_NAME WL_2D_MASS
#define THIS_PROJECT_NAME_STRING std::string("WL_2D_MASS")
#endif
